apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: lines-target
  labels:
    strimzi.io/cluster: production-ready-target
spec:
  topicName: lines
  partitions: 10
  replicas: 2
  config:
    retention.ms: 14400000
    segment.bytes: 1073741824
