apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: secure-topic-reader
  labels:
    strimzi.io/cluster: production-ready
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic lines using consumer group secure-group
      - resource:
          type: topic
          name: lines
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: lines
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: secure-group
          patternType: literal
        operation: Read
        host: "*"
