== Environment

=== Lab environment

The lab environment provides a virtualized setup for developing and running Kafka applications on OpenShift.
It consists of:

* an OpenShift cluster with one master node and three worker nodes;
* a workstation;

During the lab you will interact with the OpenShift cluster via CLI from the workstation and with the OpenShift web console from the browser available on your station.
Make note of the URLs that you will use during the lab.

|===
| Machine | URL | Access
| Workstation | `workstation-<GUID>.rhpds.opentlc.com` | SSH (port 22)
| Master (OpenShift console) | `master00-<GUID>.generic.opentlc.com` | HTTPS (port 8443)
|===

Every lab assumes that you have access to the workstation via SSH for CLI interaction and to the OpenShift web console.

Before you start any lab, make sure you are logged into the workstation via SSH with the key that has been provided by the instructors.

     ssh -i <path/to/lab/key.pem> cloud-user@workstation-<GUID>.rhpds.opentlc.com

For OpenShift access, the lab provides an `admin` user.
It should be used for logging in both via CLI and web console.
The password will be provided by the instructors.

[NOTE]
.Remember your GUID
At the start of the lab you have been provided with a GUID, which uniquely identifies your lab environment.
In the following instructions, replace the `<GUID>` placeholder with your GUID.
For example, if your GUID is `a2b3`, the URL `workstation-<GUID>.example.com` becomes `workstation-a2b3.example.com`.

Now, let's start the lab.
