== Management and monitoring

This lab will be focused on:

* Instrumenting a cluster to support metrics
* Deploying Prometheus and Grafana
* Importing prebuilt Grafana dashboard definitions for Kafka and ZooKeeper.

While OpenShift uses Grafana and Prometheus internally, we need to use separate Prometheus and Grafana instances for our applications.
For this exercise, we will install our own instance of Prometheus and Grafana for Kafka monitoring in the same namespace as the Kafka cluster.
In this case it is 'amq-streams'.


=== Instrumenting the Kafka cluster

We will reconfigure the `production-ready` cluster to advertise metrics.

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/clusters/production-ready-monitored.yaml
----

=== Installing Prometheus

To install Prometheus, we use the instructions of the Strimzi labs: https://strimzi.io/docs/0.11.1/#kafka_metrics_configuration

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/metrics/prometheus.yaml
----

Then we create a route for the Prometheus service.
Make sure your project is set to 'amq-streams'.

----
oc expose svc prometheus
----

=== Install Grafana

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/metrics/grafana.yaml
----

Then we create a route for the Grafana service.
Make sure your project is set to 'amq-streams'.

----
oc expose svc grafana
----

Now, let's configure the Grafana dashboard.
Get the route:

----
oc get routes
----

It should be similar to : "http://grafana-amq-streams.apps-<GUID>.generic.opentlc.com"

Login as `admin`/`admin` to the Grafana dashboard on your browser with the URL from above.
You can also change the admin password if you'd like.

=== Setting up Grafana to monitor Kafka

Create the Prometheus datasource.
Go to the `Gear' icon on the left and then pick *Datasources*.

Choose Prometheus as data source type and then fill following values:

     name: prometheus
     url:  `http://prometheus-amq-streams.apps-<GUID>.generic.opentlc.com`

Save and Test.
You should see a 'data source tested' message.

Import Dashboard definitions.
Go to the + on the top left and choose "import".
Copy the JSON from this location `https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.11.1/metrics/examples/grafana/strimzi-kafka.json`
Pick prometheus as the datasource and finish
You should see the dashboard with data like in the screenshots.

Similarly to create kafka-zookeeper dashboards, import the corresponding definition.
Go to the + on the top left and choose "import".
Copy the JSON from this location `https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.11.1/metrics/examples/grafana/strimzi-zookeeper.json`
Pick prometheus as the datasource and finish.
You should see the dashboard with data like in the screenshots.
