== Separating namespace: watching multiple namespaces

In the examples we've seen so far, the cluster operator as well as the Kafka cluster, topic and user CRDs were deployed in the same project/namespace.
AMQ Streams allows the cluster operator to monitor a set of separate namespaces, which could be useful for teams that want to manage their own individual clusters.
Each namespace is independent of the other, and resources created in each of them will result in the creation of clusters, topics and users in that specific namespace.

=== Creating the namespaces

Let's set up two separate projects: `team-1` and `team-2`.

Execute the following commands:

----
oc new-project team-1
----

and

----
oc new-project team-2
----

For this lab, we will still deploy the cluster operator in the `amq-streams` project.
If you've already done so, we will reconfigure it.
So let's revert to the original project `amq-streams`.

----
oc project amq-streams
----

=== Configuring the cluster operator to watch multiple namespaces

First, update the configuration files to reference the target namespace of the cluster operator.
If you've already done so in the first lab, skip this step.

----
sed -i 's/namespace: .*/namespace: amq-streams/' install/cluster-operator/*RoleBinding*.yaml
----

Next, alter the file `install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml` to point to the monitored projects.
You need do so by editing the file and changing the value of `STRIMZI_NAMESPACE` from its original form:

----
...
       env:
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
...
----

to:

----
...
        env:
        - name: STRIMZI_NAMESPACE
          value: amq-streams,team-1,team-2
...
----

In this lab, you can do so either by editing the file with `vim` or  by running the following command:

----
cat > install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml <<'EOF'
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
    strimzi.io/kind: cluster-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: registry.access.redhat.com/amq7/amq-streams-cluster-operator:1.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_NAMESPACE
          value: amq-streams,team-1,team-2
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "120000"
        - name: STRIMZI_OPERATION_TIMEOUT_MS
          value: "300000"
        - name: STRIMZI_DEFAULT_ZOOKEEPER_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-zookeeper:1.1.0-kafka-2.1.1
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.0.0=registry.access.redhat.com/amq7/amq-streams-kafka:1.1.0-kafka-2.0.0
            2.1.1=registry.access.redhat.com/amq7/amq-streams-kafka:1.1.0-kafka-2.1.1
        - name: STRIMZI_KAFKA_CONNECT_IMAGES
          value: |
            2.0.0=registry.access.redhat.com/amq7/amq-streams-kafka-connect:1.1.0-kafka-2.0.0
            2.1.1=registry.access.redhat.com/amq7/amq-streams-kafka-connect:1.1.0-kafka-2.1.1
        - name: STRIMZI_KAFKA_CONNECT_S2I_IMAGES
          value: |
            2.0.0=registry.access.redhat.com/amq7/amq-streams-kafka-connect-s2i:1.1.0-kafka-2.0.0
            2.1.1=registry.access.redhat.com/amq7/amq-streams-kafka-connect-s2i:1.1.0-kafka-2.1.1
        - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
          value: |
            2.0.0=registry.access.redhat.com/amq7/amq-streams-kafka-mirror-maker:1.1.0-kafka-2.0.0
            2.1.1=registry.access.redhat.com/amq7/amq-streams-kafka-mirror-maker:1.1.0-kafka-2.1.1
        - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-topic-operator:1.1.0
        - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-user-operator:1.1.0
        - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-kafka-init:1.1.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-zookeeper-stunnel:1.1.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-kafka-stunnel:1.1.0
        - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
          value: registry.access.redhat.com/amq7/amq-streams-entity-operator-stunnel:1.1.0
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
  strategy:
    type: Recreate
EOF
----

Next, install `RoleBinding`s for each of the two monitored namespaces:

----
oc apply -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n team-1
oc apply -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n team-1
oc apply -f install/cluster-operator/032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml -n team-1
----

and

----
oc apply -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n team-2
oc apply -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n team-2
oc apply -f install/cluster-operator/032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml -n team-2
----

Finally, install - or re-install and reconfigure the `cluster-operator`.

----
oc apply -f install/cluster-operator
----

Now we can deploy clusters, topics and users in each of these namespaces.
Use the console to monitor the result.

Let's deploy a new cluster in the project `team-1` first (note the namespace reference in the `oc` command).
----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/clusters/production-ready.yaml -n team-1
----

From the OpenShift console, navigate to the `team-1` project and notice the new cluster, as well as service.

Let's see that the cluster works.

Reconfigure the `timer-producer` and `log-consumer` applications to use the new cluster.

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/applications/log-consumer-team-1.yaml
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/applications/timer-producer-team-1.yaml
----

Now let's deploy a second cluster in the project `team-2` (note again the namespace reference in the `oc` command).

----
oc apply -f https://raw.githubusercontent.com/RedHatWorkshops/workshop-amq-streams/master/configurations/clusters/production-ready.yaml -n team-2
----

You should see the new cluster being created by observing the `team-2` project in the OpenShift console.
